version: '3.4'

services:
  # https://hub.docker.com/_/microsoft-mssql-server
  guiaempresarialapi.database:
    container_name: GuiaEmpresarialAPI.Database
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles: ["db"]

  guiaempresarialapi.server:
    image: ${DOCKER_REGISTRY-}guiaempresarialapiserver
    build:
      context: .
      dockerfile: src\GuiaEmpresarialAPI.Server\Dockerfile
    profiles: ["app"]