version: '3.4'

services:
  guiaempresarialapi.database:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${GUIAEMPRESARIALAPI_DB_PASSWORD}
    ports:
      - 1434:1433
    networks:
      - guiaempresarialapi.network
    volumes:
      - guiaempresarialapi.database.volume:/var/opt/mssql

  guiaempresarialapi.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    networks:
      - guiaempresarialapi.network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro

networks:
  guiaempresarialapi.network:

volumes:
  guiaempresarialapi.database.volume:
    driver: local